#!/usr/bin/env python3
"""Generate service-local contract artifacts from repo-level schemas."""

from __future__ import annotations

import json
import pprint
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
CONTRACTS_DIR = REPO_ROOT / "contracts"
FRONTEND_OUT = REPO_ROOT / "frontend" / "src" / "contracts" / "generated" / "schemas.ts"
BACKEND_OUT = REPO_ROOT / "backend" / "app" / "contracts" / "generated_schemas.py"
SYMPHONY_OUT = (
    REPO_ROOT.parent / "symphony" / "src" / "contracts" / "generated" / "schemas.ts"
)


def _schema_key(path: Path) -> str:
    raw = path.relative_to(CONTRACTS_DIR).as_posix().replace("/", "__").replace(".", "_")
    return raw.replace("-", "_")


def _ts_name(key: str) -> str:
    parts = key.split("_")
    head, *tail = parts
    return head + "".join(part[:1].upper() + part[1:] for part in tail)


def _py_name(key: str) -> str:
    return key.upper()


def load_schemas() -> list[tuple[str, dict[str, object]]]:
    schemas: list[tuple[str, dict[str, object]]] = []
    for path in sorted(CONTRACTS_DIR.rglob("*.json")):
        schemas.append((_schema_key(path), json.loads(path.read_text(encoding="utf-8"))))
    return schemas


def render_frontend(schemas: list[tuple[str, dict[str, object]]]) -> str:
    lines = [
        "// This file is generated by scripts/generate_contract_artifacts.py.",
        "// Do not edit by hand.",
        "",
        "export type SchemaEnum<T> = T extends { enum: readonly (infer U)[] } ? U : never;",
        "export type SchemaProperties<T> = T extends { properties: infer P } ? P : never;",
        "",
    ]
    for key, schema in schemas:
        lines.append(
            f"export const {_ts_name(key)} = {json.dumps(schema, indent=2)} as const;",
        )
        lines.append("")
    alias_specs = [
        (
            "ActivityExecutionRunPayloadStatus",
            "activityExecutionRunPayloadSchemaJson",
            "status",
        ),
        (
            "ActivityExecutionRunPayloadExecutorKind",
            "activityExecutionRunPayloadSchemaJson",
            "executor_kind",
        ),
        (
            "ExecutionCallbackPayloadStatus",
            "executionCallbackPayloadSchemaJson",
            "status",
        ),
        (
            "ExecutionDispatchAcceptanceAdapterMode",
            "executionDispatchAcceptanceSchemaJson",
            "adapter_mode",
        ),
    ]
    for alias_name, schema_name, property_name in alias_specs:
        lines.append(
            f'export type {alias_name} = SchemaEnum<SchemaProperties<typeof {schema_name}>["{property_name}"]>;',
        )
    lines.append("")
    lines.append("export const contractSchemaIds = {")
    for key, _schema in schemas:
        lines.append(f'  "{key}": "{_ts_name(key)}",')
    lines.append("} as const;")
    lines.append("")
    return "\n".join(lines)


def render_backend(schemas: list[tuple[str, dict[str, object]]]) -> str:
    lines = [
        '"""Generated contract schema snapshots."""',
        "",
        "# This file is generated by scripts/generate_contract_artifacts.py.",
        "# Do not edit by hand.",
        "",
        "from __future__ import annotations",
        "",
        "SCHEMAS = {",
    ]
    for key, schema in schemas:
        rendered = pprint.pformat(schema, width=100, sort_dicts=False)
        indented = "\n".join(f"    {line}" for line in rendered.splitlines())
        lines.append(f'    "{key}":')
        lines.append(indented + ",")
    lines.append("}")
    lines.append("")
    for key, _schema in schemas:
        lines.append(f'{_py_name(key)} = SCHEMAS["{key}"]')
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    schemas = load_schemas()
    FRONTEND_OUT.parent.mkdir(parents=True, exist_ok=True)
    BACKEND_OUT.parent.mkdir(parents=True, exist_ok=True)
    FRONTEND_OUT.write_text(render_frontend(schemas), encoding="utf-8")
    BACKEND_OUT.write_text(render_backend(schemas), encoding="utf-8")
    outputs = [FRONTEND_OUT, BACKEND_OUT]
    if SYMPHONY_OUT.parent.parent.exists():
        SYMPHONY_OUT.parent.mkdir(parents=True, exist_ok=True)
        SYMPHONY_OUT.write_text(render_frontend(schemas), encoding="utf-8")
        outputs.append(SYMPHONY_OUT)
    print(f"Generated {len(schemas)} contract artifacts across {len(outputs)} outputs.")
    for output in outputs:
        print(f" - {output.relative_to(REPO_ROOT) if output.is_relative_to(REPO_ROOT) else output}")


if __name__ == "__main__":
    main()
