#!/usr/bin/env python3
"""Generate service-local contract artifacts from repo-level schemas."""

from __future__ import annotations

import json
import pprint
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
CONTRACTS_DIR = REPO_ROOT / "contracts"
FRONTEND_OUT = REPO_ROOT / "frontend" / "src" / "contracts" / "generated" / "schemas.ts"
BACKEND_OUT = REPO_ROOT / "backend" / "app" / "contracts" / "generated_schemas.py"
SYMPHONY_OUT = (
    REPO_ROOT.parent / "symphony" / "src" / "contracts" / "generated" / "schemas.ts"
)


def _schema_key(path: Path) -> str:
    raw = path.relative_to(CONTRACTS_DIR).as_posix().replace("/", "__").replace(".", "_")
    return raw.replace("-", "_")


def _ts_name(key: str) -> str:
    parts = key.split("_")
    head, *tail = parts
    return head + "".join(part[:1].upper() + part[1:] for part in tail)


def _py_name(key: str) -> str:
    return key.upper()


def _exported_type_name(key: str, schema: dict[str, Any]) -> str:
    title = schema.get("title")
    if isinstance(title, str) and title.strip():
        normalized = title.strip()
        return normalized.removeprefix("SiloForge")
    return "".join(part[:1].upper() + part[1:] for part in key.split("_") if part)


def _required_fields(schema: dict[str, object]) -> set[str]:
    required = schema.get("required")
    if not isinstance(required, list):
        return set()
    return {item for item in required if isinstance(item, str)}


def _ts_type_expr(schema: dict[str, Any], *, inline: bool = False) -> str:
    expected = schema.get("type")
    if "enum" in schema and isinstance(schema["enum"], list):
        values = " | ".join(json.dumps(item) for item in schema["enum"])
        return values or "never"
    if isinstance(expected, list):
        return " | ".join(_ts_type_expr({"type": item, **{k: v for k, v in schema.items() if k != "type"}}) for item in expected)
    if expected == "string":
        return "string"
    if expected == "integer" or expected == "number":
        return "number"
    if expected == "boolean":
        return "boolean"
    if expected == "null":
        return "null"
    if expected == "array":
        items = schema.get("items")
        if isinstance(items, dict):
            return f"Array<{_ts_type_expr(items)}>"
        return "unknown[]"
    if expected == "object":
        properties = schema.get("properties")
        if not isinstance(properties, dict):
            return "Record<string, unknown>"
        required = _required_fields(schema)
        parts: list[str] = []
        for key, child in properties.items():
            if not isinstance(child, dict):
                continue
            optional = "" if key in required else "?"
            parts.append(f"{key}{optional}: {_ts_type_expr(child)};")
        body = " ".join(parts)
        return f"{{ {body} }}" if inline else "{ " + body + " }"
    return "unknown"


def _py_literal_alias(values: list[Any]) -> str:
    rendered = ", ".join(repr(item) for item in values)
    return f"Literal[{rendered}]"


def load_schemas() -> list[tuple[str, dict[str, object]]]:
    schemas: list[tuple[str, dict[str, object]]] = []
    for path in sorted(CONTRACTS_DIR.rglob("*.json")):
        schemas.append((_schema_key(path), json.loads(path.read_text(encoding="utf-8"))))
    return schemas


def render_frontend(schemas: list[tuple[str, dict[str, object]]]) -> str:
    lines = [
        "// This file is generated by scripts/generate_contract_artifacts.py.",
        "// Do not edit by hand.",
        "",
        "export type SchemaEnum<T> = T extends { enum: readonly (infer U)[] } ? U : never;",
        "export type SchemaProperties<T> = T extends { properties: infer P } ? P : never;",
        "",
    ]
    for key, schema in schemas:
        lines.append(
            f"export const {_ts_name(key)} = {json.dumps(schema, indent=2)} as const;",
        )
        lines.append("")
    alias_specs = [
        (
            "ActivityExecutionRunPayloadStatus",
            "activityExecutionRunPayloadSchemaJson",
            "status",
        ),
        (
            "ActivityExecutionRunPayloadExecutorKind",
            "activityExecutionRunPayloadSchemaJson",
            "executor_kind",
        ),
        (
            "ExecutionCallbackPayloadStatus",
            "executionCallbackPayloadSchemaJson",
            "status",
        ),
        (
            "ExecutionDispatchAcceptanceAdapterMode",
            "executionDispatchAcceptanceSchemaJson",
            "adapter_mode",
        ),
    ]
    for alias_name, schema_name, property_name in alias_specs:
        lines.append(
            f'export type {alias_name} = SchemaEnum<SchemaProperties<typeof {schema_name}>["{property_name}"]>;',
        )
    lines.append("")
    type_specs = [
        (
            "ActivityExecutionRunPayload",
            "activityExecutionRunPayloadSchemaJson",
        ),
        (
            "ExecutionCallbackPayload",
            "executionCallbackPayloadSchemaJson",
        ),
        (
            "ExecutionDispatchAcceptance",
            "executionDispatchAcceptanceSchemaJson",
        ),
        (
            "ExecutionDispatchRequest",
            "executionDispatchRequestSchemaJson",
        ),
    ]
    schema_map = {key: schema for key, schema in schemas}
    for type_name, schema_name in type_specs:
        matching_key = next(
            key for key, _schema in schemas if _ts_name(key) == schema_name
        )
        lines.append(
            f"export type {type_name} = {_ts_type_expr(schema_map[matching_key], inline=True)};"
        )
    lines.append("")
    for key, schema in schemas:
        type_name = _exported_type_name(key, schema)
        if type_name in {item[0] for item in type_specs}:
            continue
        lines.append(
            f"export type {type_name} = {_ts_type_expr(schema, inline=True)};"
        )
    lines.append("")
    lines.append("export const contractSchemaIds = {")
    for key, _schema in schemas:
        lines.append(f'  "{key}": "{_ts_name(key)}",')
    lines.append("} as const;")
    lines.append("")
    return "\n".join(lines)


def render_backend(schemas: list[tuple[str, dict[str, object]]]) -> str:
    lines = [
        '"""Generated contract schema snapshots."""',
        "",
        "# This file is generated by scripts/generate_contract_artifacts.py.",
        "# Do not edit by hand.",
        "",
        "from __future__ import annotations",
        "",
        "from typing import Literal, TypeAlias",
        "",
        "SCHEMAS = {",
    ]
    for key, schema in schemas:
        rendered = pprint.pformat(schema, width=100, sort_dicts=False)
        indented = "\n".join(f"    {line}" for line in rendered.splitlines())
        lines.append(f'    "{key}":')
        lines.append(indented + ",")
    lines.append("}")
    lines.append("")
    for key, _schema in schemas:
        lines.append(f'{_py_name(key)} = SCHEMAS["{key}"]')
    lines.append("")
    enum_specs = [
        (
            "ACTIVITY_EXECUTION_RUN_PAYLOAD_STATUS",
            "activity__execution_run_payload_schema_json",
            "status",
        ),
        (
            "ACTIVITY_EXECUTION_RUN_PAYLOAD_EXECUTOR_KIND",
            "activity__execution_run_payload_schema_json",
            "executor_kind",
        ),
        (
            "EXECUTION_CALLBACK_PAYLOAD_STATUS",
            "execution__callback_payload_schema_json",
            "status",
        ),
        (
            "EXECUTION_DISPATCH_ACCEPTANCE_ADAPTER_MODE",
            "execution__dispatch_acceptance_schema_json",
            "adapter_mode",
        ),
    ]
    schema_lookup = {key: schema for key, schema in schemas}
    for alias_name, schema_key, property_name in enum_specs:
        properties = schema_lookup[schema_key].get("properties", {})
        if not isinstance(properties, dict):
            continue
        property_schema = properties.get(property_name)
        if not isinstance(property_schema, dict):
            continue
        enum_values = property_schema.get("enum")
        if not isinstance(enum_values, list):
            continue
        lines.append(f"{alias_name}_VALUES = {tuple(enum_values)!r}")
        lines.append(
            f"{alias_name}: TypeAlias = {_py_literal_alias(enum_values)}"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    schemas = load_schemas()
    FRONTEND_OUT.parent.mkdir(parents=True, exist_ok=True)
    BACKEND_OUT.parent.mkdir(parents=True, exist_ok=True)
    FRONTEND_OUT.write_text(render_frontend(schemas), encoding="utf-8")
    BACKEND_OUT.write_text(render_backend(schemas), encoding="utf-8")
    outputs = [FRONTEND_OUT, BACKEND_OUT]
    if SYMPHONY_OUT.parent.parent.exists():
        SYMPHONY_OUT.parent.mkdir(parents=True, exist_ok=True)
        SYMPHONY_OUT.write_text(render_frontend(schemas), encoding="utf-8")
        outputs.append(SYMPHONY_OUT)
    print(f"Generated {len(schemas)} contract artifacts across {len(outputs)} outputs.")
    for output in outputs:
        print(f" - {output.relative_to(REPO_ROOT) if output.is_relative_to(REPO_ROOT) else output}")


if __name__ == "__main__":
    main()
